---
## Run lastpass-cli from host machine
- hosts: localhost
  connection: local
  tasks:
  - include: lastpass-tasks.yml
- hosts: default
  sudo: yes
  vars_files:
  - my-vars.yml
  roles:
  - jsnshrmn.centos7
  tasks:
  - name: Link /srv to /vagrant/srv
    file: src=/vagrant/srv dest=/srv state=link force=yes
  - include: d7-tasks.yml
  - include: secure-tunnel-tasks.yml
  - name: Disable selinux for vagrant
    selinux: state=disabled
  - name: Add apache user to vagrant group
    command: usermod -a -G vagrant apache
