---
- hosts: localhost
  tasks:
  - include: lastpass-tasks.yml
- hosts: default
  sudo: yes
  vars_files:
  - base-server-vars.yml
  vars_prompt:
  - name: ngrok_authtoken
    prompt: "Ngrok signup https://dashboard.ngrok.com/user/signup\nngrok authtoken"
    private: yes
  tasks:
  - include: base-server-tasks.yml
  - include: d7-tasks.yml
  - include: ngrok-tasks.yml
  handlers:
  - include: base-server-handlers.yml
