---
- hosts: localhost
  tasks:
  - include: lastpass-tasks.yml
- hosts: default
  sudo: yes
  vars_files:
  - base-server-vars.yml
  - my-vars.yml
  tasks:
  - include: base-server-tasks.yml
  - include: d7-tasks.yml
  - include: secure-tunnel-tasks.yml
  handlers:
  - include: base-server-handlers.yml
