---
- name: Kill ngrok if running
  sudo_user: vagrant
  command: killall ngrok
  ignore_errors: yes
- name: Ensure /home/vagrant/.ngrok2 exists
  file: path=/home/vagrant/.ngrok2 state=directory
- name: Configure ngrok
  template:
    src: assets/ngrok.yml.j2
    dest: /home/vagrant/.ngrok2/ngrok.yml
