core = 7.x

api = 2
projects[drupal][version] = "7.66"

; Modules
projects[admin_menu][version] = "3.0-rc6"
projects[alt_http_client][version] = "1.0"
projects[better_exposed_filters][version] = "3.6"
projects[ctools][version] = "1.14"
projects[ckeditor][version] = "1.18"
projects[custom_search][version] = "1.20"
projects[date][version] = "2.10"
projects[fontyourface][version] = "2.8"
projects[editableviews][version] = "1.0-beta10"
projects[email][version] = "1.3"
projects[entity][version] = "1.9"
projects[entityreference][version] = "1.5"
projects[eu_cookie_compliance][version] = "1.28"
projects[exclude_node_title][version] = "1.9"
projects[jquery_update][version] = "2.7"
projects[libraries][version] = "2.5"
projects[link][version] = "1.6"
projects[module_missing_message_fixer][version] = "1.7"
projects[node_clone][version] = "1.0"
projects[node_expire][version] = "1.8"
projects[node_export][version] = "3.1"
projects[oembed][version] = "0.1-beta3"
projects[owlcarousel][version] = "2.x-dev"
projects[panels_bootstrap_layouts][version] = "3.0"
projects[paragraphs][version] = "1.0-rc5"
projects[pathauto][version] = "1.3"
projects[primo_sso][version] = "1.0"
projects[print][version] = "2.0"
projects[realname][version] = "1.4"
projects[redirect][version] = "1.0-rc3"
projects[rules][version] = "2.12"
projects[simplehtmldom][version] = "1.12"
projects[user_import][version] = "3.2"
projects[userprotect][version] = "1.2"
projects[uuid][version] = "1.0-alpha6"
projects[variable][version] = "2.5"
projects[views][version] = "3.22"
projects[views_accordion][version] = "1.6"
projects[views_bootstrap][version] = "3.1"
projects[views_data_export][version] = "3.2"
projects[views_dependent_filters][version] = "1.1"
projects[views_autocomplete_filters][version] = "1.2"
projects[views_block_filter_block][version] = "1.0-beta2"
projects[webform][version] = "4.19"
projects[webform_rules][version] = "1.6"

; Themes
projects[bootstrap][version] = "3.22"

projects[oulib_cas][type] = "module"
projects[oulib_cas][download][type] = "git"
projects[oulib_cas][download][url] = "https://github.com/OULibraries/oulib_cas.git"
projects[oulib_cas][download][branch] = "7.x-0.x"

projects[views_bootstrap][download][type] = "git"
projects[views_bootstrap][download][url] = "https://github.com/OULibraries/views_bootstrap.git"
projects[views_bootstrap][type] = "module"

libraries[fontawesome][download][type] = "git"
libraries[fontawesome][download][url] = "https://github.com/FortAwesome/Font-Awesome.git"
libraries[fontawesome][download][branch] = "master"
libraries[fontawesome][download][revision] = "a65bd93d81e9e6bd5ebfa41757a4474960b973b4"
libraries[fontawesome][directory_name] = "fontawesome"
libraries[fontawesome][type] = "library"

libraries[cas][download][type] = "git"
libraries[cas][download][url] = "https://github.com/apereo/phpCAS"
libraries[cas][directory_name] = "CAS"
libraries[cas][type] = "library"
