; This file was auto-generated by drush make

core = 7.x

api = 2
projects[drupal][version] = "7.59"

; Modules
projects[views_bulk_operations][version] = "3.3"
projects[addressfield][version] = "1.1"
projects[admin_menu][version] = "3.0-rc4"
projects[ctools][version] = "1.11"
projects[calendar][version] = "3.5"
projects[cas][version] = "1.5"
projects[cas_attributes][version] = "1.0-rc3"
projects[cas_roles][version] = "1.2"
projects[ckeditor][version] = "1.16"
projects[colorbox][version] = "2.10"
projects[custom_breadcrumbs] = "2.0-beta1"
projects[date][version] = "2.8"
projects[date_ical][version] = "3.3"
projects[devel][version] = "1.5"
projects[fontyourface][version] = "2.8"
projects[editableviews][version] = "1.0-beta10"
projects[email][version] = "1.3"
projects[entity][version] = "1.9"
projects[entityreference][version] = "1.1"
projects[exclude_node_title][version] = "1.7"
projects[feeds][version] = "2.0-beta1"
projects[feeds_tamper][version] = "1.0"
projects[field_conditional_state][version] = "2.1"
projects[field_group][version] = "1.5"
projects[field_permissions][version] = "1.0-beta2"
projects[find_content][version] = "1.4"
projects[fitvids][version] = "1.17"
projects[flag][version] = "3.9"
projects[google_analytics][version] = "2.3"
projects[panels][version] = "3.9"
projects[imagefield_focus][version] = "1.0"
projects[job_scheduler][version] = "2.0-alpha3"
projects[jquery_update][version] = "2.7"
projects[libraries][version] = "2.2"
projects[link][version] = "1.3"
projects[mosaicflow][version] = "1.0-beta2"
projects[node_expire][version] = "1.7"
projects[node_export][version] = "3.0"
projects[panels_bootstrap_layouts][version] = "3.0"
projects[paragraphs][version] = "1.0-rc5"
projects[pathauto][version] = "1.2"
projects[rate][version] = "1.7"
projects[realname][version] = "1.2"
projects[redirect][version] = "1.0-rc3"
projects[rules][version] = "2.7"
projects[slick][version] = "2.0"
projects[slick_extras] = "2.0-beta4"
projects[slick_views] = "2.0"
projects[telephone][version] = "1.0-alpha1"
projects[token][version] = "1.5"
projects[token_filter][version] = "1.1"
projects[uuid][version] = "1.0-alpha6"
projects[views][version] = "3.17"
projects[views_accordion][version] = "1.0"
projects[views_bootstrap][version] = "3.1"
projects[views_data_export][version] = "3.1"
projects[votingapi] = "2.12"
projects[webform][version] = "4.12"

; Themes
projects[bootstrap][version] = "3.10"

; Themes
projects[oulib_intranet][type] = "theme"
projects[oulib_intranet][download][type] = "git"
projects[oulib_intranet][download][url] = "https://github.com/OULibraries/oulib_intranet.git"
projects[oulib_intranet][download][branch] = "master"
;projects[oulib_intranet][download][revision] = "80e5223c73b3b9d6a7cdc35fc138d594c4af192e"

; Projects
projects[intranet_custom][type] = "module"
projects[intranet_custom][download][type] = "git"
projects[intranet_custom][download][url] = "https://github.com/OULibraries/intranet_custom.git"
projects[intranet_custom][download][branch] = "master"

; Projects
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[loginblock][download][type] = "git"
projects[loginblock][download][url] = "https://github.com/OULibraries/loginblock.git"
projects[loginblock][type] = "module"

projects[views_bootstrap][download][type] = "git"
projects[views_bootstrap][download][url] = "https://github.com/OULibraries/views_bootstrap.git"
projects[views_bootstrap][type] = "module"

projects[ou_layouts][type] = "module"
projects[ou_layouts][download][type] = "git"
projects[ou_layouts][download][url] = "https://github.com/OULibraries/ou_layouts.git"
projects[ou_layouts][download][branch] = "master"
;projects[ou_layouts][download][revision] = "4005a71973ad1bcc246a83bbcc89213322a996ce"

projects[oulib_cas][type] = "module"
projects[oulib_cas][download][type] = "git"
projects[oulib_cas][download][url] = "https://github.com/OULibraries/oulib_cas.git"
projects[oulib_cas][download][branch] = "7.x-0.x"

projects[oulib_blocks][type] = "module"
projects[oulib_blocks][download][type] = "git"
projects[oulib_blocks][download][url] = "https://github.com/OULibraries/oulib_blocks.git"
projects[oulib_blocks][download][branch] = "7.x-0.x"
;projects[oulib_blocks][download][revision] = "2dac3ec5b5ece8707eb62db4ecfa9ab5f6f48bd9"

projects[better_contact][type] = "module"
projects[better_contact][download][type] = "git"
projects[better_contact][download][url] = "https://github.com/OULibraries/better_contact.git"

; Libraries
libraries[slick][download][type] = "git"
libraries[slick][download][url] = "https://github.com/kenwheeler/slick.git"
libraries[slick][download][branch] = "master"
libraries[slick][directory_name] = "slick"
libraries[slick][type] = "library"

libraries[jquery.easing][download][type] = "git"
libraries[jquery.easing][download][url] = "https://github.com/gdsmith/jquery.easing.git"
libraries[jquery.easing][download][branch] = "master"
libraries[jquery.easing][directory_name] = "jquery.easing"
libraries[jquery.easing][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[iCalcreator][download][type] = "git"
libraries[iCalcreator][download][url] = "https://github.com/iCalcreator/iCalcreator.git"
libraries[iCalcreator][download][branch] = "master"
libraries[iCalcreator][download][revision] = "e3dbec2cb3bb91a8bde989e467567ae8831a4026"
libraries[iCalcreator][directory_name] = "iCalcreator"
libraries[iCalcreator][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[fitvids][download][type] = "git"
libraries[fitvids][download][url] = "https://github.com/davatron5000/FitVids.js.git"
libraries[fitvids][download][branch] = "master"
libraries[fitvids][directory_name] = "fitvids"
libraries[fitvids][type] = "library"

libraries[colorbox][download][type] = "git"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox.git"
libraries[colorbox][download][branch] = "master"
libraries[colorbox][download][revision]= "d9a4e2dfaabc63751eb82eb37f0fb4de6f31f203"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

libraries[bootstrap][download][type] = "get"
libraries[bootstrap][download][url] = "https://github.com/twbs/bootstrap/releases/download/v3.3.1/bootstrap-3.3.1-dist.zip"
libraries[bootstrap][directory_name] = "bootstrap"
libraries[bootstrap][type] = "library"
