; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.66"

; Modules
projects[views_bulk_operations][version] = "3.5"
projects[addressfield][version] = "1.3"
projects[admin_menu][version] = "3.0-rc6"
projects[alt_http_client][version] = "1.0"
projects[ctools][version] = "1.14"
projects[calendar][version] = "3.5"
projects[cas][version] = "1.7"
projects[cas_attributes][version] = "1.0-rc3"
projects[cas_roles][version] = "1.2"
projects[charts][version] = "2.1"
projects[ckeditor][version] = "1.18"
projects[colorbox][version] = "2.10"
projects[custom_breadcrumbs] = "2.0-beta1"
projects[date][version] = "2.10"
projects[date_ical][version] = "3.9"
projects[devel][version] = "1.5"
projects[fontyourface][version] = "2.8"
projects[editableviews][version] = "1.0-beta10"
projects[email][version] = "1.3"
projects[entity][version] = "1.9"
projects[entityreference][version] = "1.5"
projects[feeds][version] = "2.0-beta4"
projects[feeds_tamper][version] = "1.2"
projects[field_conditional_state][version] = "2.1"
projects[field_group][version] = "1.6"
projects[field_permissions][version] = "1.0"
projects[find_content][version] = "1.7"
projects[fitvids][version] = "1.17"
projects[flag][version] = "3.9"
projects[panels][version] = "3.9"
projects[google_analytics][version] = "2.1"
projects[google_analytics_reports][version] = "3.0"
projects[highcharts][version] = "1.0-alpha6"
projects[imagefield_focus][version] = "1.0"
projects[job_scheduler][version] = "2.0"
projects[jquery_update][version] = "2.7"
projects[label_help][version] = "1.2"
projects[libraries][version] = "2.5"
projects[link][version] = "1.6"
projects[manualcrop][version] = "1.7"
projects[mathfield][version] = "1.0"
projects[module_missing_message_fixer][version] = "1.7"
projects[node_export][version] = "3.1"
projects[panels_bootstrap_layouts][version] = "3.0"
projects[paragraphs][version] = "1.0-rc5"
projects[paragraphs][patch][] = "https://www.drupal.org/files/issues/2018-11-26/paragraphs-count-php71-3010938-3.patch"
projects[pathauto][version] = "1.3"
projects[realname][version] = "1.4"
projects[redirect][version] = "1.0-rc3"
projects[rules][version] = "2.12"
projects[telephone][version] = "1.0-alpha1"
projects[token][version] = "1.7"
projects[token_filter][version] = "1.1"
projects[user_picture_field][version] = "1.0-rc1"
projects[uuid][version] = "1.2"
projects[views][version] = "3.22"
projects[views_accordion][version] = "1.6"
projects[views_bootstrap][version] = "3.1"
projects[views_data_export][version] = "3.2"
projects[webform][version] = "4.19"

; Themes
projects[bootstrap][version] = "3.22"

; Themes
projects[oulib_intranet][type] = "theme"
projects[oulib_intranet][download][type] = "git"
projects[oulib_intranet][download][url] = "https://github.com/OULibraries/oulib_intranet.git"
projects[oulib_intranet][download][branch] = "master"
;projects[oulib_intranet][download][revision] = "80e5223c73b3b9d6a7cdc35fc138d594c4af192e"

projects[oulib_admin_intranet][type] = "theme"
projects[oulib_admin_intranet][download][type] = "git"
projects[oulib_admin_intranet][download][url] = "https://github.com/OULibraries/oulib_admin_intranet.git"
projects[oulib_admin_intranet][download][branch] = "master"
;projects[oulib_admin_intranet][download][revision] = "80e5223c73b3b9d6a7cdc35fc138d594c4af192e"

; Projects
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[intranet_custom][type] = "module"
projects[intranet_custom][download][type] = "git"
projects[intranet_custom][download][url] = "https://github.com/OULibraries/intranet_custom.git"
projects[intranet_custom][download][branch] = "master"

projects[oulib_authorizedsender][type] = "module"
projects[oulib_authorizedsender][download][type] = "git"
projects[oulib_authorizedsender][download][url] = "https://github.com/OULibraries/oulib_authorizedsender.git"
projects[oulib_authorizedsender][download][branch] = "7.x-1.x"

projects[oulib_cas][type] = "module"
projects[oulib_cas][download][type] = "git"
projects[oulib_cas][download][url] = "https://github.com/OULibraries/oulib_cas.git"
projects[oulib_cas][download][branch] = "7.x-0.x"

projects[loginblock][download][type] = "git"
projects[loginblock][download][url] = "https://github.com/OULibraries/loginblock.git"
projects[loginblock][type] = "module"

projects[views_bootstrap][download][type] = "git"
projects[views_bootstrap][download][url] = "https://github.com/OULibraries/views_bootstrap.git"
projects[views_bootstrap][type] = "module"

projects[ou_layouts][type] = "module"
projects[ou_layouts][download][type] = "git"
projects[ou_layouts][download][url] = "https://github.com/OULibraries/ou_layouts.git"
;projects[ou_layouts][download][revision] = "4005a71973ad1bcc246a83bbcc89213322a996ce"
projects[ou_layouts][download][branch] = "master"

projects[bi_stats][type] = "module"
projects[bi_stats][download][type] = "git"
projects[bi_stats][download][url] = "https://github.com/OULibraries/bi_stats.git"
projects[bi_stats][download][branch] = "master"

projects[oulib_blocks][type] = "module"
projects[oulib_blocks][download][type] = "git"
projects[oulib_blocks][download][url] = "https://github.com/OULibraries/oulib_blocks.git"
projects[oulib_blocks][download][branch] = "7.x-0.x"
;projects[oulib_blocks][download][revision] = "2dac3ec5b5ece8707eb62db4ecfa9ab5f6f48bd9"

projects[better_contact][type] = "module"
projects[better_contact][download][type] = "git"
projects[better_contact][download][url] = "https://github.com/OULibraries/better_contact.git"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[iCalcreator][download][type] = "git"
libraries[iCalcreator][download][url] = "https://github.com/iCalcreator/iCalcreator.git"
libraries[iCalcreator][download][branch] = "master"
libraries[iCalcreator][download][revision] = "e3dbec2cb3bb91a8bde989e467567ae8831a4026"
libraries[iCalcreator][directory_name] = "iCalcreator"
libraries[iCalcreator][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[fitvids][download][type] = "git"
libraries[fitvids][download][url] = "https://github.com/davatron5000/FitVids.js.git"
libraries[fitvids][download][branch] = "master"
libraries[fitvids][directory_name] = "fitvids"
libraries[fitvids][type] = "library"

libraries[colorbox][download][type] = "git"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox.git"
libraries[colorbox][download][branch] = "master"
libraries[colorbox][download][revision]= "d9a4e2dfaabc63751eb82eb37f0fb4de6f31f203"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; required by Charts module
libraries[highcharts][download][type] = "file"
libraries[highcharts][download][url] = "http://code.highcharts.com/highcharts.js"
libraries[highcharts][directory_name] = "highcharts/js"

; required by ManualCrop
;libraries[jquery.imagesLoaded][download][type] = "git"
;libraries[jquery.imagesLoaded][download][url] = "https://github.com/desandro/imagesloaded.git"
;libraries[jquery.imagesLoaded][directory_name] = "jquery.imagesloaded"
;libraries[jquery.imagesLoaded][type] = "library"

; required by ManualCrop
;libraries[jquery.imgareaselect][download][type] = "get"
;libraries[jquery.imgareaselect][download][url] = "http://odyniec.net/projects/imgareaselect/jquery.imgareaselect-0.9.10.zip"
;libraries[jquery.imgareaselect][directory_name] = "jquery.imgareaselect"
;libraries[jquery.imgareaselect][type] = "library"

; required by ManualCrop
libraries[jquery.imagesLoaded][download][type] = "get"
libraries[jquery.imagesLoaded][download][url] = "https://github.com/desandro/imagesloaded/archive/v2.1.1.zip"
libraries[jquery.imagesLoaded][directory_name] = "jquery.imagesloaded"
libraries[jquery.imagesLoaded][type] = "library"

; required by ManualCrop
libraries[jquery.imgareaselect][download][type] = "get"
libraries[jquery.imgareaselect][download][url] = "https://github.com/odyniec/imgareaselect/archive/v0.9.11-rc.1.zip"
libraries[jquery.imgareaselect][directory_name] = "jquery.imgareaselect"
libraries[jquery.imgareaselect][type] = "library"

libraries[bootstrap][download][type] = "get"
libraries[bootstrap][download][url] = "https://github.com/twbs/bootstrap/releases/download/v3.3.1/bootstrap-3.3.1-dist.zip"
libraries[bootstrap][directory_name] = "bootstrap"
libraries[bootstrap][type] = "library"

libraries[cas][download][type] = "git"
libraries[cas][download][url] = "https://github.com/apereo/phpCAS"
libraries[cas][directory_name] = "CAS"
libraries[cas][type] = "library"
