core = 7.x

api = 2
projects[drupal][version] = "7.53"

; Modules
projects[addressfield][version] = "1.1"
projects[admin_menu][version] = "3.0-rc4"
projects[auto_entitylabel][version] = "1.3"
projects[ctools][version] = "1.11"
projects[captcha][version] = "1.2"
projects[conditional_fields][version] = "3.0-alpha2"
projects[ckeditor][version] = "1.16"
projects[colorbox][version] = "2.10"
projects[custom_add_another][version] = "1.0"
projects[custom_search][version] = "1.18"
projects[date][version] = "2.8"
projects[date_ical][version] = "3.3"
projects[devel][version] = "1.5"
projects[fontyourface][version] = "2.8"
projects[email][version] = "1.3"
projects[entity][version] = "1.6"
projects[entity_view_mode][version] = "1.0-rc1"
projects[entityreference][version] = "1.1"
projects[feeds][version] = "2.0-beta1"
projects[feeds_entity_processor][version] = "1.x-dev"
projects[feeds_tamper][version] = "1.0"
projects[field_collection][version] = "1.0-beta12"
projects[field_conditional_state][version] = "2.1"
projects[field_default_token][version] = "1.2"
projects[field_group][version] = "1.5"
projects[field_permissions][version] = "1.0-beta2"
projects[file_formatters][version] = "1.0"
projects[find_content][version] = "1.4"
projects[fitvids][version] = "1.17"
projects[flag][version] = "3.8"
projects[fontawesome][version] = "1.0"
projects[geofield][version] = "2.3"
projects[geophp][version] = "1.7"
projects[google_analytics][version] = "2.3"
projects[panels][version] = "3.6"
projects[imagefield_focus][version] = "1.0"
projects[job_scheduler][version] = "2.0-alpha3"
projects[jquery_update][version] = "2.7"
projects[leaflet_more_maps][version] = "1.10"
projects[libraries][version] = "2.2"
projects[link][version] = "1.3"
projects[mass_contact][version] = "1.1"
projects[node_expire][version] = "1.7"
projects[node_export][version] = "3.0"
projects[owlcarousel][version] = "1.2"
projects[panels_bootstrap_layouts][version] = "3.0"
projects[paragraphs][version] = "1.0-rc4"
projects[pathauto][version] = "1.2"
projects[primo_sso][version] = "1.0"
projects[realname][version] = "1.2"
projects[redirect][version] = "1.0-rc3"
projects[rules][version] = "2.7"
projects[simplehtmldom][version] = "1.12"
projects[spamspan][version] = "1.2"
projects[stringoverrides][version] = "1.8"
projects[strongarm][version] = "2.0"
projects[telephone][version] = "1.0-alpha1"
projects[tipsy][version] = "1.0-rc1"
projects[token][version] = "1.5"
projects[token_filter][version] = "1.1"
projects[user_import][version] = "2.3"
projects[userprotect][version] = "1.2"
projects[uuid][version] = "1.0-alpha6"
projects[variable][version] = "2.5"
projects[views][version] = "3.14"
projects[views_accordion][version] = "1.0"
projects[views_bootstrap][version] = "3.1"
projects[views_data_export][version] = "3.0"
projects[webform][version] = "4.12"
projects[webform_rules][version] = "1.6"

; Themes
projects[bootstrap][version] = "3.10"
projects[oulib_base][type] = "theme"
projects[oulib_base][download][type] = "git"
projects[oulib_base][download][url] = "https://github.com/OULibraries/oulib_base.git"

projects[ou_layouts][type] = "module"
projects[ou_layouts][download][type] = "git"
projects[ou_layouts][download][url] = "https://github.com/OULibraries/ou_layouts.git"
projects[ou_layouts][download][branch] = "user-acceptance"

projects[views_bootstrap][download][type] = "git"
projects[views_bootstrap][download][url] = "https://github.com/OULibraries/views_bootstrap.git"
projects[views_bootstrap][type] = "module"

projects[oulib_blocks][type] = "module"
projects[oulib_blocks][download][type] = "git"
projects[oulib_blocks][download][url] = "https://github.com/OULibraries/oulib_blocks.git"
projects[oulib_blocks][download][branch] = "7.x-0.x"
;projects[oulib_blocks][download][revision] = "2dac3ec5b5ece8707eb62db4ecfa9ab5f6f48bd9"

projects[loginblock][download][type] = "git"
projects[loginblock][download][url] = "https://github.com/OULibraries/loginblock.git"
projects[loginblock][type] = "module"

projects[ldap][type] = "module"
projects[ldap][download][type] = "git"
projects[ldap][download][url] = "https://github.com/OULibraries/ldap.git"
projects[ldap][download][branch] = "7.x-2.x-oulib"
;projects[ldap][download][revision] = "6f6c7c6a2bf6d2cadcefa1f0567554b68b190aeb"

; Libraries
libraries[colorbox][download][type] = "git"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox.git"
libraries[colorbox][download][branch] = "master"
libraries[colorbox][download][revision]= "d9a4e2dfaabc63751eb82eb37f0fb4de6f31f203"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

libraries[fontawesome][download][type] = "git"
libraries[fontawesome][download][url] = "https://github.com/FortAwesome/Font-Awesome.git"
libraries[fontawesome][download][branch] = "master"
libraries[fontawesome][download][revision] = "a65bd93d81e9e6bd5ebfa41757a4474960b973b4"
libraries[fontawesome][directory_name] = "fontawesome"
libraries[fontawesome][type] = "library"

libraries[bootstrap][download][type] = "get"
libraries[bootstrap][download][url] = "https://github.com/twbs/bootstrap/releases/download/v3.3.1/bootstrap-3.3.1-dist.zip"
libraries[bootstrap][directory_name] = "bootstrap"
libraries[bootstrap][type] = "library"
