; This file was auto-generated by drush make

core = 7.x

api = 2
projects[drupal][version] = "7.65"

; Modules
projects[admin_menu][version] = "3.0-rc6"
projects[better_exposed_filters][version] = "3.6"
projects[ctools][version] = "1.14"
projects[calendar][version] = "3.5"
projects[ckeditor][version] = "1.18"
projects[colorbox][version] = "2.13"
projects[date][version] = "2.10"
projects[devel][version] = "1.7"
projects[fontyourface][version] = "2.8"
projects[editableviews][version] = "1.0-beta10"
projects[email][version] = "1.3"
projects[entity][version] = "1.9"
projects[entity_view_mode][version] = "1.0-rc1"
projects[entityreference][version] = "1.5"
projects[exclude_node_title][version] = "1.9"
projects[features][version] = "2.11"
projects[feeds][version] = "2.0-beta4"
projects[feeds_entity_processor][version] = "1.x-dev"
projects[feeds_tamper][version] = "1.2"
projects[field_group][version] = "1.6"
projects[field_permissions][version] = "1.0"
projects[find_content][version] = "1.7"
projects[fitvids][version] = "1.17"
projects[fontawesome][version] = "1.0"
projects[panels][version] = "3.9"
projects[imagefield_focus][version] = "1.0"
projects[jquery_update][version] = "2.7"
projects[libraries][version] = "2.5"
projects[link][version] = "1.6"
projects[manualcrop][version] = "1.7"
projects[module_missing_message_fixer][version] = "1.7"
projects[oembed][version] = "0.1-beta3"
projects[owlcarousel][version] = "2.x-dev"
projects[panels_bootstrap_layouts][version] = "3.0"
projects[paragraphs][version] = "1.0-rc5"
projects[pathauto][version] = "1.3"
projects[realname][version] = "1.4"
projects[rules][version] = "2.12"
projects[slick][version] = "2.1"
projects[slick_extras][version] = "2.0"
projects[slick_views][version] = "2.1"
projects[spamspan][version] = "1.3"
projects[token][version] = "1.7"
projects[token_filter][version] = "1.1"
projects[userprotect][version] = "1.2"
projects[variable][version] = "2.5"
projects[video_embed_field][version] = "2.0-beta11"
projects[views][version] = "3.22"
projects[views_bootstrap][version] = "3.2"
projects[views_data_export][version] = "3.2"
projects[webform][version] = "4.19"
projects[webform_rules][version] = "1.6"
projects[cas][version] = "1.7"
projects[cas_attributes][version] = "1.0-rc3"
projects[cas_roles][version] = "1.2"
projects[primo_sso][version] = "1.0"
projects[google_tag][version] = "1.4"

; Themes
projects[bootstrap][version] = "3.23"
projects[entity_iframe_theme][version] = "1.0"

projects[views_bootstrap][download][type] = "git"
projects[views_bootstrap][download][url] = "https://github.com/OULibraries/views_bootstrap.git"
projects[views_bootstrap][type] = "module"

projects[oulib_poetics][type] = "theme"
projects[oulib_poetics][download][type] = "git"
projects[oulib_poetics][download][url] = "https://github.com/OULibraries/oulib_poetics.git"
projects[oulib_poetics][download][branch] = "master"

;Projects
projects[bef_bootstrap_fix][type] = "module"
projects[bef_bootstrap_fix][download][type] = "git"
projects[bef_bootstrap_fix][download][url] = "https://github.com/OULibraries/bef_bootstrap_fix.git"
projects[bef_bootstrap_fix][download][branch] = "master"

projects[better_contact][type] = "module"
projects[better_contact][download][type] = "git"
projects[better_contact][download][url] = "https://github.com/OULibraries/better_contact.git"

projects[ou_layouts][type] = "module"
projects[ou_layouts][download][type] = "git"
projects[ou_layouts][download][url] = "https://github.com/OULibraries/ou_layouts.git"
projects[ou_layouts][download][branch] = "user-acceptance"
;projects[ou_layouts][download][revision] = "4005a71973ad1bcc246a83bbcc89213322a996ce"

projects[oulib_blocks][type] = "module"
projects[oulib_blocks][download][type] = "git"
projects[oulib_blocks][download][url] = "https://github.com/OULibraries/oulib_blocks.git"
projects[oulib_blocks][download][branch] = "7.x-0.x"
;projects[oulib_blocks][download][revision] = "2dac3ec5b5ece8707eb62db4ecfa9ab5f6f48bd9"

projects[oulib_cas][type] = "module"
projects[oulib_cas][download][type] = "git"
projects[oulib_cas][download][url] = "https://github.com/OULibraries/oulib_cas.git"
projects[oulib_cas][download][branch] = "7.x-0.x"

projects[intranet_custom][type] = "module"
projects[intranet_custom][download][type] = "git"
projects[intranet_custom][download][url] = "https://github.com/OULibraries/intranet_custom.git"
projects[intranet_custom][download][branch] = "master"

; Libraries
; Please fill the following out. Type may be one of ge
; and url is the url of the download.
libraries[slick][download][type] = "get"
libraries[slick][download][url] = "https://github.com/kenwheeler/slick/archive/1.8.0.zip"
libraries[slick][directory_name] = "slick"
libraries[slick][type] = "library"

; Please fill the following out. Type may be one of ge
; and url is the url of the download.
libraries[easing][download][type] = ""
libraries[easing][download][url] = ""
libraries[easing][directory_name] = "easing"
libraries[easing][type] = "library"

; Please fill the following out. Type may be one of ge
; and url is the url of the download.
libraries[mousewheel][download][type] = ""
libraries[mousewheel][download][url] = ""
libraries[mousewheel][directory_name] = "mousewheel"
libraries[mousewheel][type] = "library"

libraries[colorbox][download][type] = "git"
libraries[colorbox][download][url] = "https://github.com/jackmoore/colorbox.git"
libraries[colorbox][download][tag] = "1.6.4"
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"
libraries[colorbox][patch][] ="https://www.drupal.org/files/issues/Adding-ARIA-labels-to-colorbox-library-1.6.4.patch"

libraries[iCalcreator][download][type] = "git"
libraries[iCalcreator][download][url] = "https://github.com/iCalcreator/iCalcreator.git"
libraries[iCalcreator][download][branch] = "master"
libraries[iCalcreator][download][revision] = "e3dbec2cb3bb91a8bde989e467567ae8831a4026"
libraries[iCalcreator][directory_name] = "iCalcreator"
libraries[iCalcreator][type] = "library"

libraries[fitvids][download][type] = "git"
libraries[fitvids][download][url] = "https://github.com/davatron5000/FitVids.js.git"
libraries[fitvids][download][branch] = "master"
libraries[fitvids][directory_name] = "fitvids"
libraries[fitvids][type] = "library"

libraries[fontawesome][download][type] = "git"
libraries[fontawesome][download][url] = "https://github.com/FortAwesome/Font-Awesome.git"
libraries[fontawesome][download][branch] = "master"
libraries[fontawesome][download][revision] = "a65bd93d81e9e6bd5ebfa41757a4474960b973b4"
libraries[fontawesome][directory_name] = "fontawesome"
libraries[fontawesome][type] = "library"

libraries[owl-carousel][download][type] = "get"
libraries[owl-carousel][download][url] = "https://github.com/OwlCarousel2/OwlCarousel2/archive/2.3.4.zip"
libraries[owl-carousel][download][subtree] = "OwlCarousel2-2.3.4/dist"
libraries[owl-carousel][directory_name] = "owlcarousel"
libraries[owl-carousel][type] = "library"

libraries[bootstrap][download][type] = "get"
libraries[bootstrap][download][url] = "https://github.com/twbs/bootstrap/releases/download/v3.3.1/bootstrap-3.3.1-dist.zip"
libraries[bootstrap][directory_name] = "bootstrap"
libraries[bootstrap][type] = "library"

libraries[cas][download][type] = "git"
libraries[cas][download][url] = "https://github.com/apereo/phpCAS"
libraries[cas][directory_name] = "CAS"
libraries[cas][type] = "library"

; required by ManualCrop
libraries[jquery.imagesLoaded][download][type] = "get"
libraries[jquery.imagesLoaded][download][url] = "https://github.com/desandro/imagesloaded/archive/v2.1.1.zip"
libraries[jquery.imagesLoaded][directory_name] = "jquery.imagesloaded"
libraries[jquery.imagesLoaded][type] = "library"

; required by ManualCrop
libraries[jquery.imgareaselect][download][type] = "get"
libraries[jquery.imgareaselect][download][url] = "https://github.com/odyniec/imgareaselect/archive/v0.9.11-rc.1.zip"
libraries[jquery.imgareaselect][directory_name] = "jquery.imgareaselect"
libraries[jquery.imgareaselect][type] = "library"

; Features
projects[paragraph_bundles_feature][type] = "module"
projects[paragraph_bundles_feature][download][type] = "git"
projects[paragraph_bundles_feature][download][url] = "https://github.com/OULibraries/paragraph-bundles-feature.git"
projects[paragraph_bundles_feature][download][branch] = "master"
