; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.43"

; Modules
projects[ctools][version] = "1.9"
projects[fontyourface][version] = "2.8"
projects[views][version] = "3.13"

; Modules
projects[loginblock][type] = "module"
projects[loginblock][download][type] = "git"
projects[loginblock][download][url] = "https://github.com/OULibraries/loginblock.git"
;projects[loginblock][download][revision] = "f5291d5a03f77878535d93f6fd2e2be49c31ec87"

projects[oulib_blocks][type] = "module"
projects[oulib_blocks][download][type] = "git"
projects[oulib_blocks][download][url] = "https://github.com/OULibraries/oulib_blocks.git"
projects[oulib_blocks][download][branch] = "7.x-0.x"
;projects[oulib_blocks][download][revision] = "4173dc543968d3ab9a5a34b6208432ad43b7b301"

; Themes
projects[bootstrap][version] = "3.0"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[oulib_repo][download][type] = "git"
projects[oulib_repo][download][url] = "https://github.com/OULibraries/oulib_repo.git"
projects[oulib_repo][type] = "theme"

