; This file was auto-generated by drush make
core = 7.x
api = 2
projects[drupal][version] = "7.39"

; Modules
projects[advanced_help][version] = "1.3"
projects[arrange_fields][version] = "1.15"
projects[ctools][version] = "1.9"
projects[bundle_copy][version] = "1.1"
projects[context][version] = "3.6"
projects[date][version] = "2.8"
projects[devel][version] = "1.5"
projects[email][version] = "1.3"
projects[entity][version] = "1.6"
projects[entity2text][version] = "1.0-alpha2"
projects[entity_rules][version] = "1.0-alpha4"
projects[entityform][version] = "2.0-rc1"
projects[entityreference][version] = "1.1"
projects[features][version] = "2.6"
projects[panels][version] = "3.5"
projects[jquery_update][version] = "2.6"
projects[ldap][version] = "2.0-beta8"
projects[menu_item_visibility][version] = "1.0-beta1"
projects[options_element][version] = "1.12"
projects[rules][version] = "2.9"
projects[select_or_other][version] = "2.22"
projects[strongarm][version] = "2.0"
projects[token][version] = "1.6"
projects[views][version] = "3.11"
projects[views_bootstrap][version] = "3.1"
projects[webform][version] = "4.10"
projects[webform_validation][version] = "1.10"

; Themes
projects[bootstrap][version] = "3.0"
