; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.41"

; Modules
projects[admin_menu][version] = "3.0-rc4"
projects[ctools][version] = "1.9"
projects[captcha][version] = "1.3"
projects[ckeditor][version] = "1.16"
projects[date][version] = "2.9-rc1+3-dev"
projects[fontyourface][version] = "2.8"
projects[editableviews][version] = "1.0-beta10"
projects[email][version] = "1.3"
projects[entity][version] = "1.6"
projects[exclude_node_title][version] = "1.9"
projects[features][version] = "2.6"
projects[field_conditional_state][version] = "2.1"
projects[field_permissions][version] = "1.0-beta2"
projects[flag][version] = "3.6"
projects[panels][version] = "3.5"
projects[imagefield_focus][version] = "1.0"
projects[jquery_update][version] = "3.0-alpha2"
projects[pdf_to_imagefield][version] = "3.3"
projects[rules][version] = "2.9"
projects[token][version] = "1.6"
projects[token_filter][version] = "1.1"
projects[views][version] = "3.11"
projects[webform][version] = "4.10"
projects[webform_entity][version] = "1.x-dev"


; Themes
projects[bootstrap][version] = "3.0"

; Modules
projects[loginblock][type] = "module"
projects[loginblock][download][type] = "git"
projects[loginblock][download][url] = "https://github.com/OULibraries/loginblock.git"
projects[loginblock][download][revision] = "f5291d5a03f77878535d93f6fd2e2be49c31ec87"

projects[ldap][type] = "module"
projects[ldap][download][type] = "git"
projects[ldap][download][url] = "https://github.com/OULibraries/ldap.git"
projects[ldap][download][branch] = "7.x-2.x-oulib"
;projects[ldap][download][revision] = "6f6c7c6a2bf6d2cadcefa1f0567554b68b190aeb"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[oulib_signage][download][type] = "git"
projects[oulib_signage][download][url] = "https://github.com/OULibraries/oulib_signage.git"
projects[oulib_signage][type] = "theme"
projects[oulib_signage][download][branch] = "master"
