; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.52"

; Modules
projects[admin_menu][version] = "3.0-rc5"
projects[cas][version] = "1.5"
projects[cas_attributes][version] = "1.0-rc3"
projects[cas_roles][version] = "1.2"
projects[ctools][version] = "1.11"
projects[captcha][version] = "1.3"
projects[ckeditor][version] = "1.17"
projects[date][version] = "2.9"
projects[fontyourface][version] = "2.8"
projects[editableviews][version] = "1.0-beta10"
projects[email][version] = "1.3"
projects[entity][version] = "1.6"
projects[exclude_node_title][version] = "1.9"
projects[features][version] = "2.10"
projects[field_conditional_state][version] = "2.1"
projects[field_permissions][version] = "1.0-beta2"
projects[flag][version] = "3.9"
projects[panels][version] = "3.8"
projects[imagefield_focus][version] = "1.0"
projects[jquery_update][version] = "3.0-alpha2"
projects[pdf_to_imagefield][version] = "3.3"
projects[redirect][version] = "1.0-rc3"
projects[rules][version] = "2.9"
projects[token][version] = "1.6"
projects[token_filter][version] = "1.1"
projects[views][version] = "3.15"
projects[webform][version] = "4.12"
projects[webform_entity][version] = "1.x-dev"


; Themes
projects[bootstrap][version] = "3.8"

projects[oulib_cas][type] = "module"
projects[oulib_cas][download][type] = "git"
projects[oulib_cas][download][url] = "https://github.com/OULibraries/oulib_cas.git"
projects[oulib_cas][download][branch] = "7.x-0.x"

projects[intranet_custom][type] = "module"
projects[intranet_custom][download][type] = "git"
projects[intranet_custom][download][url] = "https://github.com/OULibraries/intranet_custom.git"
projects[intranet_custom][download][branch] = "user-acceptance"

; Modules
projects[loginblock][type] = "module"
projects[loginblock][download][type] = "git"
projects[loginblock][download][url] = "https://github.com/OULibraries/loginblock.git"
projects[loginblock][download][revision] = "f5291d5a03f77878535d93f6fd2e2be49c31ec87"

projects[ldap][type] = "module"
projects[ldap][download][type] = "git"
projects[ldap][download][url] = "https://github.com/OULibraries/ldap.git"
projects[ldap][download][branch] = "7.x-2.x-oulib"
;projects[ldap][download][revision] = "6f6c7c6a2bf6d2cadcefa1f0567554b68b190aeb"

projects[oulib_authorizedsender][type] = "module"
projects[oulib_authorizedsender][download][type] = "git"
projects[oulib_authorizedsender][download][url] = "https://github.com/OULibraries/oulib_authorizedsender.git"
projects[oulib_authorizedsender][download][branch] = "7.x-1.x"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[oulib_signage][download][type] = "git"
projects[oulib_signage][download][url] = "https://github.com/OULibraries/oulib_signage.git"
projects[oulib_signage][type] = "theme"
projects[oulib_signage][download][branch] = "user-acceptance"
