; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.43"

; Modules
projects[views_bulk_operations][version] = "3.3"
projects[admin_menu][version] = "3.0-rc4"
projects[charts][version] = "2.0-rc1"
projects[ctools][version] = "1.9"
projects[ckeditor][version] = "1.16"
projects[devel][version] = "1.5"
projects[fontyourface][version] = "2.8"
projects[editableviews][version] = "1.0-beta10"
projects[email][version] = "1.3"
projects[entity][version] = "1.6"
projects[entity_view_mode][version] = "1.0-rc1"
projects[entityreference][version] = "1.1"
projects[exclude_node_title][version] = "1.7"
projects[features][version] = "2.2"
projects[feeds][version] = "2.0-beta1"
projects[feeds_tamper][version] = "1.0"
projects[field_conditional_state][version] = "2.1"
projects[field_default_token][version] = "1.2"
projects[field_permissions][version] = "1.0-beta2"
projects[file_formatters][version] = "1.0"
projects[find_content][version] = "1.4"
projects[fitvids][version] = "1.17"
projects[flag][version] = "3.5"
projects[fontawesome][version] = "1.0"
projects[google_analytics][version] = "2.1"
projects[gootle_analytics_reports][version] = "3.0"
projects[highcharts][version] = "1.0-alpha6"
projects[panels][version] = "3.4"
projects[imagefield_focus][version] = "1.0"
projects[job_scheduler][version] = "2.0-alpha3"
projects[jquery_update][version] = "2.7"
projects[leaflet_more_maps][version] = "1.10"
projects[libraries][version] = "2.2"
projects[link][version] = "1.3"
projects[node_expire][version] = "1.7"
projects[node_export][version] = "3.0"
projects[owlcarousel][version] = "1.2"
projects[panels_bootstrap_layouts][version] = "3.0"
projects[pathauto][version] = "1.2"
projects[realname][version] = "1.2"
projects[redirect][version] = "1.0-rc3"
projects[rules][version] = "2.7"
projects[simplehtmldom][version] = "1.12"
projects[spamspan][version] = "1.2"
projects[strongarm][version] = "2.0"
projects[telephone][version] = "1.0-alpha1"
projects[tipsy][version] = "1.0-rc1"
projects[token][version] = "1.5"
projects[token_filter][version] = "1.1"
projects[user_import][version] = "2.3"
projects[userprotect][version] = "1.2"
projects[uuid][version] = "1.0-alpha6"
projects[variable][version] = "2.5"
projects[views][version] = "3.11"
projects[views_accordion][version] = "1.0"
projects[views_bootstrap][version] = "3.1"
projects[views_data_export][version] = "3.0-beta9"
projects[webform][version] = "4.12"
projects[field_group][version] = "1.5"
projects[paragraphs][version] = "1.0-rc4"

; Themes
projects[bootstrap][version] = "3.0"

; Themes
projects[oulib_intranet][type] = "theme"
projects[oulib_intranet][download][type] = "git"
projects[oulib_intranet][download][url] = "https://github.com/OULibraries/oulib_intranet.git"
projects[oulib_intranet][download][branch] = "user-acceptance"
;projects[oulib_intranet][download][revision] = "80e5223c73b3b9d6a7cdc35fc138d594c4af192e"

; Projects
projects[ldap][type] = "module"
projects[ldap][download][type] = "git"
projects[ldap][download][url] = "https://github.com/OULibraries/ldap.git"
projects[ldap][download][branch] = "7.x-2.x-oulib"
;projects[ldap][download][revision] = "6f6c7c6a2bf6d2cadcefa1f0567554b68b190aeb"

projects[leaflet][type] = "module"
projects[leaflet][download][type] = "git"
projects[leaflet][download][url] = "https://github.com/OULibraries/leaflet.git"
projects[leaflet][download][branch] = "7.x-1.x-oulib"
;projects[leaflet][download][revision] = "bef9d5cba1850e69d1b40369f81ef5a4a640ef25"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[loginblock][download][type] = "git"
projects[loginblock][download][url] = "https://github.com/OULibraries/loginblock.git"
projects[loginblock][type] = "module"

projects[views_bootstrap][download][type] = "git"
projects[views_bootstrap][download][url] = "https://github.com/OULibraries/views_bootstrap.git"
projects[views_bootstrap][type] = "module"

projects[ou_layouts][type] = "module"
projects[ou_layouts][download][type] = "git"
projects[ou_layouts][download][url] = "https://github.com/OULibraries/ou_layouts.git"
projects[ou_layouts][download][branch] = "user-acceptance"
;projects[ou_layouts][download][revision] = "4005a71973ad1bcc246a83bbcc89213322a996ce"

projects[suma_stats][type] = "module"
projects[suma_stats][download][type] = "git"
projects[suma_stats][download][url] = "https://github.com/OULibraries/suma_stats.git"
projects[suma_stats][download][branch] = "user-acceptance"
;projects[suma_stats][download][revision] = "6f6c7c6a2bf6d2cadcefa1f0567554b68b190aeb"

projects[suma_stats][type] = "module"
projects[suma_stats][download][type] = "git"
projects[suma_stats][download][url] = "https://github.com/OULibraries/gastats.git"
projects[suma_stats][download][branch] = "user-acceptance"
;projects[suma_stats][download][revision] = "6f6c7c6a2bf6d2cadcefa1f0567554b68b190aeb"


projects[oulib_blocks][type] = "module"
projects[oulib_blocks][download][type] = "git"
projects[oulib_blocks][download][url] = "https://github.com/OULibraries/oulib_blocks.git"
projects[oulib_blocks][download][branch] = "7.x-0.x"
;projects[oulib_blocks][download][revision] = "2dac3ec5b5ece8707eb62db4ecfa9ab5f6f48bd9"

projects[better_contact][type] = "module"
projects[better_contact][download][type] = "git"
projects[better_contact][download][url] = "https://github.com/OULibraries/better_contact.git"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;libraries[leaflet][download][type] = "git"
;libraries[leaflet][download][url] = "https://github.com/Leaflet/Leaflet.git"
;libraries[leaflet][download][branch] = "master"
;libraries[leaflet][download][revision] = "8a5fdfc6e3db2807b8f0dd617474e4ab2949142b"
libraries[leaflet][download][type] = "get"
libraries[leaflet][download][url] = "https://lib.ou.edu/documents/leaflet-0.7.3.zip"
libraries[leaflet][directory_name] = "leaflet"
libraries[leaflet][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[fitvids][download][type] = "git"
libraries[fitvids][download][url] = "https://github.com/davatron5000/FitVids.js.git"
libraries[fitvids][download][branch] = "master"
libraries[fitvids][directory_name] = "fitvids"
libraries[fitvids][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[fontawesome][download][type] = "git"
libraries[fontawesome][download][url] = "https://github.com/FortAwesome/Font-Awesome.git"
libraries[fontawesome][download][branch] = "master"
libraries[fontawesome][download][revision] = "a65bd93d81e9e6bd5ebfa41757a4474960b973b4"
libraries[fontawesome][directory_name] = "fontawesome"
libraries[fontawesome][type] = "library"

libraries[owl-carousel][download][type] = "get"
libraries[owl-carousel][download][url] = "https://github.com/OwlFonk/OwlCarousel/raw/f79d5de318f2848cf24b547ec1d48d44e55b2846/owl-carousel/owl.carousel.js"
libraries[owl-carousel][directory_name] = "owl-carousel"
libraries[owl-carousel][type] = "library"

libraries[owl-carousel-min][download][type] = "get"
libraries[owl-carousel-min][download][url] = "https://github.com/OwlFonk/OwlCarousel/raw/f79d5de318f2848cf24b547ec1d48d44e55b2846/owl-carousel/owl.carousel.min.js"
libraries[owl-carousel-min][directory_name] = "owl-carousel"
libraries[owl-carousel-min][type] = "library"

libraries[owl-carousel-css][download][type] = "get"
libraries[owl-carousel-css][download][url] = "https://github.com/OwlFonk/OwlCarousel/raw/f79d5de318f2848cf24b547ec1d48d44e55b2846/owl-carousel/owl.carousel.css"
libraries[owl-carousel-css][directory_name] = "owl-carousel"
libraries[owl-carousel-css][type] = "library"

libraries[owl-carousel-theme][download][type] = "get"
libraries[owl-carousel-theme][download][url] = "https://github.com/OwlFonk/OwlCarousel/raw/f79d5de318f2848cf24b547ec1d48d44e55b2846/owl-carousel/owl.theme.css"
libraries[owl-carousel-theme][directory_name] = "owl-carousel"
libraries[owl-carousel-theme][type] = "library"

libraries[owl-carousel-trans][download][type] = "get"
libraries[owl-carousel-trans][download][url] = "https://github.com/OwlFonk/OwlCarousel/blob/f79d5de318f2848cf24b547ec1d48d44e55b2846/owl-carousel/owl.transitions.css"
libraries[owl-carousel-trans][directory_name] = "owl-carousel"
libraries[owl-carousel-trans][type] = "library"

libraries[bootstrap][download][type] = "get"
libraries[bootstrap][download][url] = "https://github.com/twbs/bootstrap/releases/download/v3.3.1/bootstrap-3.3.1-dist.zip"
libraries[bootstrap][directory_name] = "bootstrap"
libraries[bootstrap][type] = "library"


