; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.67"

; Modules
projects[views_bulk_operations][version] = "3.5"
projects[admin_menu][version] = "3.0-rc6"
projects[alt_http_client][version] = "1.0"
projects[ctools][version] = "1.14"
projects[cas][version] = "1.7"
projects[cas_attributes][version] = "1.0-rc3"
projects[cas_roles][version] = "1.2"
projects[charts][version] = "2.1"
projects[ckeditor][version] = "1.18"
projects[composer_manager][version] = "1.8"
projects[custom_breadcrumbs] = "2.0-beta1"
projects[date][version] = "2.10"
projects[devel][version] = "1.7"
projects[fontyourface][version] = "2.8"
projects[editableviews][version] = "1.0-beta10"
projects[email][version] = "1.3"
projects[entity][version] = "1.9"
projects[entity_view_mode][version] = "1.0-rc1"
projects[entityreference][version] = "1.5"
projects[exclude_node_title][version] = "1.9"
projects[feeds][version] = "2.0-beta4"
projects[feeds_tamper][version] = "1.2"
projects[field_conditional_state][version] = "2.1"
projects[field_default_token][version] = "1.3"
projects[field_group][version] = "1.6"
projects[field_permissions][version] = "1.0"
projects[file_formatters][version] = "1.0"
projects[find_content][version] = "1.7"
projects[fitvids][version] = "1.17"
projects[flag][version] = "3.9"
projects[fontawesome][version] = "1.0"
projects[google_analytics][version] = "2.6"
projects[google_analytics_reports][version] = "3.1"
projects[highcharts][version] = "1.0-alpha6"
projects[panels][version] = "3.9"
projects[imagefield_focus][version] = "1.0"
projects[job_scheduler][version] = "2.0"
projects[jquery_update][version] = "2.7"
projects[leaflet_more_maps][version] = "1.17"
projects[libraries][version] = "2.5"
projects[link][version] = "1.6"
projects[module_missing_message_fixer][version] = "1.7"
projects[node_expire][version] = "1.8"
projects[node_export][version] = "3.1"
projects[owlcarousel][version] = "2.x-dev"
projects[panels_bootstrap_layouts][version] = "3.0"
projects[paragraphs][version] = "1.0-rc5"
projects[pathauto][version] = "1.3"
projects[realname][version] = "1.4"
projects[redirect][version] = "1.0-rc3"
projects[rules][version] = "2.12"
projects[strongarm][version] = "2.0"
projects[tablegroup][version] = "1.x-dev"
projects[telephone][version] = "1.0-alpha1"
projects[tipsy][version] = "1.0-rc1"
projects[token][version] = "1.7"
projects[token_filter][version] = "1.1"
projects[userprotect][version] = "1.2"
projects[uuid][version] = "1.2"
projects[variable][version] = "2.5"
projects[views][version] = "3.22"
projects[views_accordion][version] = "1.6"
projects[views_bootstrap][version] = "3.1"
projects[views_data_export][version] = "3.2"
projects[webform][version] = "4.18"

; Themes
projects[bootstrap][version] = "3.23"

; Themes
projects[oulib_intranet][type] = "theme"
projects[oulib_intranet][download][type] = "git"
projects[oulib_intranet][download][url] = "https://github.com/OULibraries/oulib_intranet.git"
projects[oulib_intranet][download][branch] = "master"

; Projects
projects[intranet_custom][type] = "module"
projects[intranet_custom][download][type] = "git"
projects[intranet_custom][download][url] = "https://github.com/OULibraries/intranet_custom.git"
projects[intranet_custom][download][branch] = "master"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[loginblock][download][type] = "git"
projects[loginblock][download][url] = "https://github.com/OULibraries/loginblock.git"
projects[loginblock][type] = "module"

projects[views_bootstrap][download][type] = "git"
projects[views_bootstrap][download][url] = "https://github.com/OULibraries/views_bootstrap.git"
projects[views_bootstrap][type] = "module"

projects[ou_layouts][type] = "module"
projects[ou_layouts][download][type] = "git"
projects[ou_layouts][download][url] = "https://github.com/OULibraries/ou_layouts.git"
projects[ou_layouts][download][branch] = "master"

projects[suma_stats][type] = "module"
projects[suma_stats][download][type] = "git"
projects[suma_stats][download][url] = "https://github.com/OULibraries/suma_stats.git"
projects[suma_stats][download][branch] = "master"

projects[combined_stats][type] = "module"
projects[combined_stats][download][type] = "git"
projects[combined_stats][download][url] = "https://github.com/OULibraries/combined_stats.git"
projects[combined_stats][download][branch] = "master"

projects[labstats_stats][type] = "module"
projects[labstats_stats][download][type] = "git"
projects[labstats_stats][download][url] = "https://github.com/OULibraries/labstats_stats.git"
projects[labstats_stats][download][branch] = "master"

projects[trafsys][type] = "module"
projects[trafsys][download][type] = "git"
projects[trafsys][download][url] = "https://github.com/OULibraries/trafsys.git"
projects[trafsys][download][branch] = "main"

projects[libanswers_stats][type] = "module"
projects[libanswers_stats][download][type] = "git"
projects[libanswers_stats][download][url] = "https://github.com/OULibraries/libanswers_stats.git"
projects[libanswers_stats][download][branch] = "master"

projects[gastats][type] = "module"
projects[gastats][download][type] = "git"
projects[gastats][download][url] = "https://github.com/OULibraries/gastats.git"
projects[gastats][download][branch] = "master"
;projects[gastats][download][revision] = "6f6c7c6a2bf6d2cadcefa1f0567554b68b190aeb"

projects[stats_cron_caching][type] = "module"
projects[stats_cron_caching][download][type] = "git"
projects[stats_cron_caching][download][url] = "https://github.com/OULibraries/stats_cron_caching.git"
projects[stats_cron_caching][download][branch] = "master"


projects[oulib_blocks][type] = "module"
projects[oulib_blocks][download][type] = "git"
projects[oulib_blocks][download][url] = "https://github.com/OULibraries/oulib_blocks.git"
projects[oulib_blocks][download][branch] = "7.x-0.x"
;projects[oulib_blocks][download][revision] = "2dac3ec5b5ece8707eb62db4ecfa9ab5f6f48bd9"

projects[better_contact][type] = "module"
projects[better_contact][download][type] = "git"
projects[better_contact][download][url] = "https://github.com/OULibraries/better_contact.git"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[fitvids][download][type] = "git"
libraries[fitvids][download][url] = "https://github.com/davatron5000/FitVids.js.git"
libraries[fitvids][download][branch] = "master"
libraries[fitvids][directory_name] = "fitvids"
libraries[fitvids][type] = "library"

libraries[fontawesome][download][type] = "git"
libraries[fontawesome][download][url] = "https://github.com/FortAwesome/Font-Awesome.git"
libraries[fontawesome][download][branch] = "master"
libraries[fontawesome][download][revision] = "a65bd93d81e9e6bd5ebfa41757a4474960b973b4"
libraries[fontawesome][directory_name] = "fontawesome"
libraries[fontawesome][type] = "library"

libraries[owl-carousel][download][type] = "get"
libraries[owl-carousel][download][url] = "https://github.com/OwlCarousel2/OwlCarousel2/archive/2.3.4.zip"
libraries[owl-carousel][download][subtree] = "OwlCarousel2-2.3.4/dist"
libraries[owl-carousel][directory_name] = "owlcarousel"
libraries[owl-carousel][type] = "library"

libraries[bootstrap][download][type] = "get"
libraries[bootstrap][download][url] = "https://github.com/twbs/bootstrap/releases/download/v3.3.1/bootstrap-3.3.1-dist.zip"
libraries[bootstrap][directory_name] = "bootstrap"
libraries[bootstrap][type] = "library"

; required by Charts module
libraries[highcharts][download][type] = "file"
libraries[highcharts][download][url] = "http://code.highcharts.com/highcharts.js"
libraries[highcharts][directory_name] = "highcharts/js"

projects[oulib_cas][type] = "module"
projects[oulib_cas][download][type] = "git"
projects[oulib_cas][download][url] = "https://github.com/OULibraries/oulib_cas.git"
projects[oulib_cas][download][branch] = "7.x-0.x"

libraries[cas][download][type] = "git"
libraries[cas][download][url] = "https://github.com/apereo/phpCAS"
libraries[cas][directory_name] = "CAS"
libraries[cas][type] = "library"
